default:
  outputs:

    dev:
      type: postgres
      host: 192.168.31.243
      user: postgres
      password: Uhj567;134
      port: 15432
      dbname: edw_dev
      schema: stg
      threads: 6

    prod:
      type: postgres
      host: 192.168.31.243
      user: postgres
      password: Uhj567;134
      port: 15432
      dbname: edw
      schema: stg
      threads: 6

  target: dev

