default:
  outputs:

    dev:
      type: postgres
      host: 127.0.0.1
      user: postgres
      password: Uhj567;134
      port: 15432
      dbname: postgres
      schema: stg
      threads: 6

  target: dev

